<?php
/**
 * Zikula Application Framework
 *
 * @copyright (c) 2001, Zikula Development Team
 * @link http://www.zikula.org
 * @version $Id: past.php 25080 2008-12-17 09:15:43Z mateo $
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Zikula_Value_Addons
 * @subpackage News
*/

/**
 * initialise block
 *
 * @author       The Zikula Development Team
 */
function News_pastblock_init()
{
    // Security
    SecurityUtil::registerPermissionSchema('Pastblock::', 'Block title::');
}

/**
 * get information on block
 *
 * @author       The Zikula Development Team
 * @return       array       The block information
 */
function News_pastblock_info()
{
    return array('text_type'      => 'Past',
                 'module'         => 'News',
                 'text_type_long' => 'Past Articles',
                 'allow_multiple' => true,
                 'form_content'   => false,
                 'form_refresh'   => false,
                 'show_preview'   => true);
}

/**
 * display block
 *
 * @author       The Zikula Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the rendered bock
 */
function News_pastblock_display($blockinfo)
{
    // security check
    if (!SecurityUtil::checkPermission('Pastblock::', "$blockinfo[title]::", ACCESS_READ)) {
        return;
    }

    // get the number of stories shown on the frontpage
    $storyhome = pnModGetVar('News', 'storyhome', 10);

    // Break out options from our content field
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['limit'])) {
        $vars['limit'] = 10;
    }

    // call the API
    $articles = pnModAPIFunc('News', 'user', 'getall',
                             array('ihome'    => 0,
                                   'order'    => 'time',
                                   'status'   => 0,
                                   'startnum' => $storyhome,
                                   'numitems' => $vars['limit']));

    if ($articles === false) {
        return;
    }

    // loop round the return articles grouping by date
    $count        = 0;
    $news         = array();
    $newscumul    = array();
    $limitreached = false;
    foreach ($articles as $article) {
        $info  = pnModAPIFunc('News', 'user', 'getArticleInfo', $article);
        $links = pnModAPIFunc('News', 'user', 'getArticleLinks', $info);
        if (SecurityUtil::checkPermission('Stories::Story', "$info[aid]::$info[sid]", ACCESS_READ)) {
            $preformat['title'] = "<a href=\"$links[fullarticle]\">$info[title]</a>";
        } else {
            $preformat['title'] = $info['title'];
        }

        $daydate = DateUtil::formatDatetime(strtotime($info['time']), '%Y-%m-%d');

        // Reset the time
        if (!isset($currentday)) {
            $currentday = $daydate;
        }

        // If it's a different date, save the cumul and continue
        if ($currentday != $daydate) {
            $news[$currentday] = $newscumul;
            $newscumul = array();
            $currentday = $daydate;
        }
        $newscumul[] = array('info'      => $info,
                             'links'     => $links,
                             'preformat' => $preformat);
    }
    if (!isset($news[$currentday])) {
        $news[$currentday] = $newscumul;
    }

    $pnRender = pnRender::getInstance('News');
    $pnRender->assign('news', $news);

    if (empty($blockinfo['title'])) {
        $blockinfo['title'] = _PASTARTICLES;
    }
    $blockinfo['content'] = $pnRender->fetch('news_block_past.htm');

    return pnBlockThemeBlock($blockinfo);
}

/**
 * modify block settings
 *
 * @author       The Zikula Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       output      the bock form
 */
function News_pastblock_modify($blockinfo)
{
    // Break out options from our content field
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // Defaults
    if (empty($vars['limit'])) {
        $vars['limit'] = 10;
    }

    // Create output object
    $pnRender = pnRender::getInstance('News');

    // As Admin output changes often, we do not want caching.
    $pnRender->caching = false;

    // assign the approriate values
    $pnRender->assign($vars);

    // Return the output that has been generated by this function
    return $pnRender->fetch('news_block_past_modify.htm');
}

/**
 * update block settings
 *
 * @author       The Zikula Development Team
 * @param        array       $blockinfo     a blockinfo structure
 * @return       $blockinfo  the modified blockinfo structure
 */
function News_pastblock_update($blockinfo)
{
    // Get current content
    $vars = pnBlockVarsFromContent($blockinfo['content']);

    // alter the corresponding variable
    $vars['limit'] = (int)FormUtil::getPassedValue('limit', null, 'POST');

    // write back the new contents
    $blockinfo['content'] = pnBlockVarsToContent($vars);

    // clear the block cache
    $pnRender = pnRender::getInstance('News');
    $pnRender->clear_cache('news_block_past.htm');

    return $blockinfo;
}
